### PR TITLE
Broke dependencies into /lib and added unit tests

### PR DESCRIPTION
**Pull request by mycaule**
I only restructured the code into 3 files and added tests. I also checked that everything still worked with the full project. 

Please check that everything is fine for Amazon S3.

### CODE REVIEW

**Comment by mycaule** [comment]
What's the status on this?

**Comment by arvindr21** [comment]
Do you think we need to keep the `firstRefactor` branch?

**Comment by mycaule** [comment]
Yes you can delete it. 
I still have to extract the aws-sdk dependency. It should be easy now.

**Comment by arvindr21** [comment]
Ok, I will till that is done to push to NPM

**Pull request merged**
