### PR TITLE
Modifying code to accept additional form fields along with images

### PR DESCRIPTION
**Pull request by abhijeetdhumal**
I have modified fileinfo.js and index.js to accept the multiple form fields along with files. 
I have tested it and working fine. Form fields will come as a part of a JSON object of fileInfo(like title/description). If not specified then will return empty object.

### CODE REVIEW

**Comment by arvindr21** [comment]
@abhijeetdhumal can you please fix the indentation as mentioned by @simison

**Comment by abhijeetdhumal** [comment]
Sure. I will do it in some time.

Regards,
Abhijeet

On Sat, May 16, 2015 at 11:28 PM, Arvind Ravulavaru <
notifications@github.com> wrote:

> @abhijeetdhumal <https://github.com/abhijeetdhumal> can you please fix
> the indentation as mentioned by @simison <https://github.com/simison>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arvindr21/blueimp-file-upload-expressjs/pull/42#issuecomment-102659796>
> .
>



-- 
WHAT IS LIFE WITHOUT AN IMPOSSIBLE DREAM!

With Regards,

Abhijeet R Dhumal
+919850984549

**Comment by abhijeetdhumal** [comment]
I have updated the code with indentation fixing.

**Comment by arvindr21** [comment]
Thanks!

**Pull request merged**
