### PR TITLE
make lusca's csrf function work

### PR DESCRIPTION
**Pull request by mamboer**

### CODE REVIEW

**Comment by mycaule** [comment]
Where is `val` defined?

**Comment by mycaule** [comment]
Please provide an example or test case as well.

**Comment by mamboer** [comment]
Sorry for the typo, i've found a more elegant way to make csrf work, pls ignore this pull-request and close it. To make csrf work normally, we can put the csrf token into http request's headers via $.ajaxSetup, i've post my example here https://github.com/mamboer/expressjs-fileupload

**Comment by mamboer** [comment]
BTW: 
I found that blueimp-file-upload-expressjs sucks with the multer package, you should comment out the multer related codes in my example to make it run.

**Comment by mycaule** [comment]
I use that kind of code to allow cross origin requests on another express project. You should be able to tweak it, it's just about HTTP headers.

```
app.all('*', function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "X-Requested-With, Content-Type");
  res.header("Access-Control-Allow-Methods", "POST, PUT, GET, DELETE");
  next();
});
```

**Pull request closed without merging**
